### ISSUE TITLE
[Bug] Error Can't Open The Game

### ISSUE THREAD

**Issue by ditokp** [buntine/SwervinMervin#4]
Hello @buntine , A few minute ago I download this game, but I can't open it. I have python 2.7 installed and python-game.

Error Message:

Traceback (most recent call last):
  File "swervin_mervin/main.py", line 6, in <module>
    import game as g
  File "/home/dito/Documents/games/Linux Games/Linux Games (Free Open-Source)/SwervinMervin-master/swervin_mervin/game.py", line 3, in <module>
    import player as p
  File "/home/dito/Documents/games/Linux Games/Linux Games (Free Open-Source)/SwervinMervin-master/swervin_mervin/player.py", line 3, in <module>
    from enum import Enum
ImportError: No module named enum

My system specs:
OS: Ubuntu 16.04 LTS 64 Bit on Asus Laptop
Memory: 1,9 Gib
Processor: Intel® Core™ i3-2330M CPU @ 2.20GHz × 4 
Graphics: Intel® Sandybridge Mobile

**Comment by Sarthak-22** [comment]
Type this command in your Linux terminal 
`sudo apt-get install python-enum34`

**Comment by magembesolomon** [comment]
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "swervin_mervin/main.py", line 21, in <module>
    game      = g.Game(window, fps_clock)
  File "/home/arch/python/SwervinMervin-master/swervin_mervin/game.py", line 24, in __init__
    self.high_scores     = hs.HighScores()
  File "/home/arch/python/SwervinMervin-master/swervin_mervin/high_scores.py", line 9, in __init__
    self.__sort()
  File "/home/arch/python/SwervinMervin-master/swervin_mervin/high_scores.py", line 33, in __sort
    self.high_scores.sort(key=lambda hs: hs[1])
AttributeError: 'map' object has no attribute 'sort'
